[package]
name = "splunk-config"
version.workspace = true
edition.workspace = true

[dependencies]
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
directories = "6.0"
tracing = { workspace = true }

[dev-dependencies]
toml = "0.8"
