{{- if and .Values.tui.enabled .Values.tui.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk-tui.fullname" . }}-tui
  labels:
    {{- include "splunk-tui.labels" . | nindent 4 }}
    app.kubernetes.io/component: tui
  {{- with .Values.tui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.tui.service.type }}
  ports:
    - port: {{ .Values.tui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "splunk-tui.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tui
{{- end }}
